# Generated by Django 3.1.14 on 2023-05-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interaction',
            new_name='Pricing',
        ),
    ]
